spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/openmusic
    username: root
    password: qwer1234
  data:
    redis:
      host: localhost
      port: 6379
      password: qwer1234
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 342167564331-qlspdv2hpb2oki66htkc5sov3jt481jo.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
  profiles:
    include: oauth
