spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://mariadb:3306/openmusic
    username: root
    password: qwer1234
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    show-sql: true
  data:
    redis:
      host: redis
      port: 6379
      password: qwer1234
  mail:
    host: smtp.gmail.com
    port: 587
    username: open3kr@gmail.com
    password: xnyp laqm ijnp iqrb
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          timeout: 5000
          connectiontimeout: 5000
          writetimeout: 5000
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23li5KLxmSHjHiXXVI
            client-secret: 409a2f5d8f6c0c95d66b7d9c8468a878bcc6342a
          google:
            client-id: 342167564331-qlspdv2hpb2oki66htkc5sov3jt481jo.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
            redirect-uri: "http://openmusic.kro.kr:8080/login/oauth2/code/google"
          facebook:
            client-id: 474896098301878
            client-secret: 5a9eb893012c9677f16f7f3e57fc5f41
            redirect-uri: "http://openmusic.kro.kr:8080/login/oauth2/code/facebook"
            client-name: Facebook
          kakao:
            client-name: Kakao
            client-id: f36c345821a073e7c992ae5c4ee1dfb8
            client-secret: 0FsGlyhONEcAMxsbmn5C77ud4kZQBzXQ
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "http://openmusic.kro.kr:8080/login/oauth2/code/kakao"
            scope:
              - profile_nickname
              - profile_image
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  servlet:
    multipart:
      enabled: true
      location: /files
      max-file-size: 500MB
      max-request-size: 500MB

cloud:
  aws:
    region:
      static: ap-northeast-2
    stack:
      auto: false
    s3:
      bucket: open3r-openmusic
    credentials:
      access-key: AKIA3FLD6A2XWBFAAKTQ
      secret-key: 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

springdoc:
  api-docs:
    enabled: true

jwt:
  secret-key: Ndjkqoi123nNasji1230SNjn124jKm1nmnMSJjk1ijifnjASJfnjno12n3injJASDjjkhb12j3bjnNJSdnjnjnjoajofnjb
  access-token-expiration: 3600000
  refresh-token-expiration: 86400000

discord:
  token: MTI0MjA2NzgzNDM3MzQwNjc5MQ.GIByS2.xTPEZRsaG3zJy3sWolVN6ZJWrtZlQ2CZfc5_68
  channel-id: 1242070161318482031