spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/openmusic
    username: root
    password: qwer1234
  data:
    redis:
      host: localhost
      port: 6379
      password: qwer1234
jwt:
  access-expiration: 3600000
  refresh-expiration: 86400000
  secret: JK23ASfn123jaso24i231hhAu9218hASJKjqwnfna8213ijNADSjnn12390Adnj12njJKASD8124jkqkjSdj132jiSi123