spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://mariadb:3306/openmusic
    username: root
    password: qwer1234
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    show-sql: true
  data:
    redis:
      host: redis
      port: 6379
      password: qwer1234
  mail:
    host: smtp.gmail.com
    port: 587
    username: open3kr@gmail.com
    password: xnyp laqm ijnp iqrb
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          timeout: 5000
          connectiontimeout: 5000
          writetimeout: 5000
  servlet:
    multipart:
      enabled: true
      location: /files
      max-file-size: 500MB
      max-request-size: 500MB

cloud:
  aws:
    region:
      static: ap-northeast-2
    stack:
      auto: false
    s3:
      bucket: open3r-openmusic
    credentials:
      access-key: AKIA3FLD6A2XWBFAAKTQ
      secret-key: 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

springdoc:
  api-docs:
    enabled: true

jwt:
  secret-key: Ndjkqoi123nNasji1230SNjn124jKm1nmnMSJjk1ijifnjASJfnjno12n3injJASDjjkhb12j3bjnNJSdnjnjnjoajofnjb
  access-token-expiration: 180000
  refresh-token-expiration: 86400000

discord:
  token: MTI0MjA2NzgzNDM3MzQwNjc5MQ.GIByS2.xTPEZRsaG3zJy3sWolVN6ZJWrtZlQ2CZfc5_68
  channel-id: 1242070161318482031

  google:
    client-id: 1
    client-secret: 1
    redirect-uri: 1