spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/openmusic
    username: root
    password: qwer1234
  jpa:
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: localhost
      port: 6379
      password: qwer1234
jwt:
  secret: adfsk12390ksdfknlann131ionnadf0912ioasdf0i230oag93rijo1esadji12iWe\
  refresh-expiration: 86400000
  access-expiration: 3600000