spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/openmusic
    username: root
    password: qwer1234
    driver-class-name: org.mariadb.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
      password: qwer1234
  jpa:
    hibernate:
      ddl-auto: create
